### PR TITLE
Feature: User-Agent header in connector

### PR DESCRIPTION
**Pull request by vg-svitla**

### CODE REVIEW

**Review by squioc — APPROVED** [review]
LGTM

**Review by Darkheir — COMMENTED** [review]
Where is this method called ?

**Comment by vg-svitla** [comment]
> Where is this method called ?

We expect to use this as common method inside all connectors. The main goal is to add this header to requests to third party services and avoid blueprint.
It is not used in sdk however we want to include this in all required connectors

**Comment by Darkheir** [comment]
> We expect to use this as common method inside all connectors. The main goal is to add this header to requests to third party services and avoid blueprint. It is not used in sdk however we want to include this in all required connectors

Then I think it should be made public. This way users of the SDK will know this is not an implementation detail and can use it without expecting breaking changes.

A line should also be added in the changelog and a test to not break code coverage.

**Review by Darkheir — APPROVED** [review]

**Pull request merged**
